### ISSUE TITLE
[BUG]: Bring back the full pallet button on the Pallet label create 

### ISSUE THREAD

**Issue by rikp777** [rikp777/RP-Flowcontrol#31]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/rikp777/RP-Flowcontrol/blob/master/.github/support.md)

### I've found a bug and checked that ...

- [X] ... there are no open or closed issues that are related to my problem

### Description

The article amount max input should automatically be filled with the max article on pallettype. 

### Expected behaviour

Automatically fill max when clicked on button 

### Debug information

![image](https://user-images.githubusercontent.com/33726176/179461733-ff02b54e-26e4-4bbd-87a8-1bb30280119b.png)

### What browsers are you seeing the problem on?

Brave

### Proofread

- [X] I have re-read everything and I stand by my issue which is correctly formulated

**Comment by RMELimax** [comment]
optioneel: 
+180 // +100 // +50 // +10 // +1 |---|  -1 // -10 // -100 // -150

![WhatsApp Image 2022-05-03 at 11 42 11 AM](https://user-images.githubusercontent.com/78860802/179726637-d261055e-17e3-4289-bb22-e53056dd99f1.jpeg)
